version: '3.4'

services:
  postgres:
    image: postgres:15.5-alpine
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg15:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    ports:
      - '127.0.0.1:6379:6379'

volumes:
  pg15:
