version: '3.4'

services:
  postgres:
    image: postgres:15.5-alpine
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg15:/var/lib/postgresql/data

  app:
    profiles: [production]
    image: production
    build: .
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      SITE_URL: ${SITE_URL}
      DATABASE_URL: postgres://postgres@postgres/postgres
      APP_KEY: 'fesajopfasjfopesajfopeasojfopea'
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      postgres:
        condition: service_started

volumes:
  pg15:
